[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD ./src ./public"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://windowworldla.netlify.app"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 4000
  framework = "next"
  autoLaunch = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://images.unsplash.com data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://api.unsplash.com; font-src 'self'; frame-src 'self'; object-src 'none'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
